FROM python:3.11
ADD code /code
RUN pip install pyaml
RUN pip install docker
RUN pip install netaddr
RUN pip install pyroute2
RUN pip install networkx
CMD ["/bin/bash", "-c" , "sleep  20000000000000s"]